---
- hosts: all
  become: yes
 
  tasks:
   - name: i wanna install tree
     apt:
      name: tree
      state: present
   - name: install apache webserver on ubuntu
     apt:
      name: apache2
      state: present
   - name : start my webserver
     service:
      name: apache2
      state: started
