---
- hosts: all
  become: yes
 
  tasks:
   - name: i wanna install httpd on Amazon Linux
     yum:
      name: httpd
      state: present
     when: ansible_os_family=="RedHat"
   - name : start my webserver
     service: 
       name: httpd
       state: started
     when: ansible_os_family=="RedHat"
   - name: install apache webserver on ubuntu
     apt:
      name: apache2
      state: present
     when: ansible_os_family=="Debian"
   - name : start my webserver
     service:
      name: apache2
      state: started
     when: ansible_os_family=="Debian"